Seg impl lfq 0312
global-nlp/knlp pull request #2
Opened 2022-03-11 17:07 UTC by Kevin1906721262

2022-03-12 03:13 UTC, Kevin1906721262 commented on knlp/seq_labeling/inference.py
> +def knlp_seg(sentence, function_name="knlp_cut"):
这个方法自己测试用的，应该删掉的，晚点再提交下

2022-03-12 03:15 UTC, Kevin1906721262 commented on knlp/seq_labeling/inference.py
> +    seg = Segmentor(stop_words_file=get_stop_words_train_file())
这个也是自测的时候改的

2022-03-12 03:15 UTC, Kevin1906721262 commented on knlp/seq_labeling/seg.py
> +            model:
误改

2022-03-26 10:52 UTC, DukeEnglish reviewed
看一下review 修改一下，记得写注释

2022-03-26 10:52 UTC, DukeEnglish commented on knlp/seq_labeling/inference.py
> +def knlp_seg(sentence, function_name="knlp_cut"):
删除后再提交一下

2022-03-26 10:52 UTC, DukeEnglish commented on knlp/utils/util.py
> +    def insert(self, stop_words, freq):
对每个函数添加注释

2022-03-26 10:52 UTC, DukeEnglish commented on knlp/utils/util.py
> +class Trie:
注释一下这个数据结构以及应用方式吧。

2022-03-26 10:52 UTC, DukeEnglish commented on knlp/seq_labeling/seg.py
> +        # print(route)
没有用的注释 删除掉

2022-03-26 10:52 UTC, DukeEnglish commented on knlp/seq_labeling/seg.py
> +        trie = Trie()
在seq_labeling下新建一个目录，叫做trie_seg。在里面定义一个新的类来实现基于trie的分词，这里仅仅只是调用实现罢了，
参考hmm的seg实现以及定义。

2022-03-28 15:00 UTC, DukeEnglish commented on knlp/seq_labeling/inference.py
> +    if "knlp_cut".__eq__(function_name):
这个应该卸载segmentor中，你看下面有调用啊。seg的初始化

2022-03-28 15:00 UTC, DukeEnglish commented on knlp/seq_labeling/inference.py
> +
这个没有过flake8的检测吧

2022-03-28 15:00 UTC, DukeEnglish commented on knlp/seq_labeling/seg.py
> -            model: 默认会使用自己训练好的model
错误修改没有修复

2022-03-28 15:00 UTC, DukeEnglish commented on knlp/seq_labeling/seg.py
> +from math import log
log在这个文件中使用了么

2022-03-28 15:00 UTC, DukeEnglish commented on knlp/utils/util.py
> +    return KNLP_PATH + "/knlp/data/jieba_dict.txt"
为啥要叫做jieba dict呢？

2022-03-28 15:00 UTC, DukeEnglish commented on knlp/utils/util.py
> +    return KNLP_PATH + "/knlp/data/jieba_dict.txt"
你的实现和jieba的区别是什么？分析一下，这个我在你的blog中没有看到。
另外 后续有一个要做的事情是评估一下你的分词和jieba的分词的性能差异

2022-03-28 15:01 UTC, DukeEnglish commented on knlp/utils/util.py
> +    return KNLP_PATH + "/knlp/data/jieba_dict.txt"
名字可以就这样保留。不过解释一下这个dict中的数据吧，加一个注释

2022-03-28 15:11 UTC, Kevin1906721262 commented
好的，收到



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月28日(星期一) 晚上11:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [global-nlp/knlp] Seg impl lfq 0312 (PR #2)





 
@DukeEnglish commented on this pull request.
 
 
In knlp/seq_labeling/inference.py:
 &gt; @@ -23,6 +24,12 @@ def seg(sentence, function_name="jieba_cut"):      Returns: list of word        """ + +    if "knlp_cut".__eq__(function_name):  
这个应该卸载segmentor中，你看下面有调用啊。seg的初始化
 
 
In knlp/seq_labeling/inference.py:
 &gt; @@ -59,4 +67,12 @@ def ner(sentence, function_name="jieba_ner"):      if __name__ == '__main__': -    print(seg("测试分词的结果是否符合预期")) +    start_time = time.time() +    # print(seg("测试分词的结果是否符合预期")) +    print(seg("测试分词的结果是否符合预期", "knlp_cut")) +    print(int(round(time.time() * 1000)) - int(round(start_time * 1000))) +  
这个没有过flake8的检测吧
 
 
In knlp/seq_labeling/seg.py:
 &gt; @@ -103,7 +104,7 @@ def hmm_seg(cls, sentence, model=None):            Args:              sentence: string -            model: 默认会使用自己训练好的model  
错误修改没有修复
 
 
In knlp/seq_labeling/seg.py:
 &gt; @@ -9,9 +9,10 @@  # -----------------------------------------------------------------------#    import jieba - +from math import log  
log在这个文件中使用了么
 
 
In knlp/utils/util.py:
 &gt; @@ -19,10 +19,76 @@  from knlp.common.constant import KNLP_PATH     +def get_jieba_dict_file(): +    return KNLP_PATH + "/knlp/data/jieba_dict.txt"  
为啥要叫做jieba dict呢？
 
 
In knlp/utils/util.py:
 &gt; @@ -19,10 +19,76 @@  from knlp.common.constant import KNLP_PATH     +def get_jieba_dict_file(): +    return KNLP_PATH + "/knlp/data/jieba_dict.txt"  
你的实现和jieba的区别是什么？分析一下，这个我在你的blog中没有看到。
 另外 后续有一个要做的事情是评估一下你的分词和jieba的分词的性能差异
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-05-04 14:49 UTC, DukeEnglish requested changes

2022-05-04 14:49 UTC, DukeEnglish commented on knlp/seq_labeling/inference.py
> +    if "knlp_cut".__eq__(function_name):
如果在segmentor中实现了，这里就不用这样写了。

2022-05-04 14:49 UTC, DukeEnglish commented on knlp/seq_labeling/trie_seg/evaluation.md
> +| 5(两个线程) | 40026    | 53133     |
为什么要开两个线程呢？
单线程的效果如何？python的线程对于cpu密集的工作效率很低，这个分词属于io密集么？

2022-05-04 14:49 UTC, DukeEnglish commented on knlp/seq_labeling/inference.py
> +def knlp_cut(text):
knlp cut 以下的函数，看起来都是为了做比较和测试使用的，我们放在trie seg目录下，新建一个文件做evaluation.py，在里面做这几个函数的编码和运行。
这个inference.py尽量纯粹，只做inference的编码

2022-05-04 14:49 UTC, DukeEnglish commented on knlp/seq_labeling/trie_seg/evaluation.md
> +# KNLP分词
因为knlp中也会实现多种分词，所以这里我们命名上使用trie分词。全部都统一用这个吧。

2022-05-04 14:49 UTC, DukeEnglish commented on knlp/seq_labeling/trie_seg/inference.py
> +def get_DAG(sentence, trie):
这个方法是不是只有TrieInference这个类会用到啊？写到类里面作为私有方法吧

2022-05-04 15:05 UTC, DukeEnglish commented on knlp/seq_labeling/trie_seg/inference.py
> +                7: (0,0),
7 0 0 分别代表什么，可以注释一下，有一个示例

2022-05-04 15:07 UTC, DukeEnglish commented on knlp/seq_labeling/trie_seg/inference.py
> +            freq = 1 if words_freq is None else int(words_freq)
freq没有的话，为什么要置1呀？

2022-05-04 15:22 UTC, DukeEnglish commented on knlp/seq_labeling/trie_seg/inference.py
> +    P(idx) = max(P(sentence[idx:x]) + P(sentence[x:-1])) , x in DAG[idx]
这里给一个更加清晰的定义吧，
dp方程清晰一些，另外P idx的定义是？idx表示第N个字符？还是什么，这块说的不清晰

2022-05-08 13:18 UTC, DukeEnglish approved these changes

2022-05-08 13:18 UTC, merged