用继承的方法重新写了train
global-nlp/knlp pull request #7
Opened 2022-03-28 16:23 UTC by Rooki1e

把train用继承的方法写了一下，因为open是内嵌在函数中的，所以有比较多函数进行了重载

2022-04-06 17:00 UTC, DukeEnglish requested changes
把.DS文件删除

2022-04-06 17:00 UTC, DukeEnglish commented on knlp/seq_labeling/hmm/pin_train.py
> +class pin_Train(Train):
类名我们使用PinYinTrain吧

2022-04-06 17:00 UTC, DukeEnglish commented on knlp/seq_labeling/hmm/pin_train.py
> +        self._emission_pro_ = {'data':self._emission_pro, 'default':1e-200}
这里的变量命名不理解，为什么第二个下面要添加下划线？

2022-04-06 17:00 UTC, DukeEnglish commented on knlp/seq_labeling/hmm/pin_train.py
> +    args = sys.argv
输入一个写死的值进行测试

2022-04-23 09:06 UTC, Rooki1e commented
按照学长说的进行了更改，并且在本地写死值进行了调试通过了

2022-04-30 11:45 UTC, DukeEnglish commented on .idea/.gitignore
> +# 默认忽略的文件
gitignore是使用根目录下的，不要提交idea这个文件

2022-04-30 11:46 UTC, DukeEnglish commented on knlp/seq_labeling/hmm/pin_train.py
> +    a = PinYinTrain(vocab_set_path=vocab_set_path, training_data_path=training_data_path)
在test中添加一个对你的拼音输入法的测试

2022-05-18 05:18 UTC, closed without merging